### ISSUE TITLE
Improve Cypress setup

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/demo-actions-on-netlify#4]
Improvements for #3:

* [ ] support running on deploy previews protected with Basic Auth
* [ ] support both `check_suite` and `check_run` (in case "rich details" hook is off)
* [ ] set `CYPRESS_BASE_URL` outside of `set-deploy-url.js`
* [ ] cache Cypress for faster installs? see [@actions/tool-cache](https://github.com/actions/toolkit/tree/master/packages/tool-cache#cache)
* [ ] save screenshots & videos as artifacts? see [actions/upload-artifact](https://github.com/actions/upload-artifact)
* [ ] comment results on PR?  see [@actions/github](https://github.com/actions/toolkit/tree/master/packages/github)
* [ ] shared job before e2e-tests and lighthouse? see [job.needs](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idneeds)

**Comment by Siilwyn** [comment]
Running against Basic Auth will need to be handled per tool afaik, for Cypress this is done in the `run` function: https://docs.cypress.io/api/commands/visit.html#Add-basic-auth-headers

**Comment by Siilwyn** [comment]
If rich details hooks are removed in Netlify so only the commit status is updated we should be able to run with: `on: [check_suite, status]` but at the moment this causes an unexpected error. Seems that the GH Actions don't work with `status` updates yet.
